% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Dec-2021 20:15:30
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------
                                 
a=floor(rand(5)*10);
b=ones(5)*9;
c=a*b;
[row,col]=size(c);
z=zeros(row,col);
for i=1:row
    for j=1:col
       if i==j
           z(i,j)=(c(i,j));
       end
    end    
end
disp(z)